spring:
  application:
    name: oauth2-server

security:
  config:
    url: http://localhost:8090/server/consumer/get/code/
    type: authorization_code
    scope: app
  users:
    name: user
    password: 123456
    role: USER

server:
  port: 8080
